"""add what's left. autogenerated

Revision ID: 88d863ed0bb4
Revises: 075f2a1a1036
Create Date: 2022-01-09 12:23:06.578072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d863ed0bb4'
down_revision = '075f2a1a1036'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
